server:
  port: 9090
spring:
  datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/globaldb
     username: root
     password: root
  jpa:
     hibernate.ddl-auto: update
     hibernate.show_sql: true
  properties:
     hibernate.dialect : org.hibernate.dialect.MySQL8Dialect   
  mvc:
     view:
         prefix: /WEB-INF/jsp/
         suffix: .jsp